### ISSUE TITLE
OperationalError: no such table: wsj

### ISSUE THREAD

**Issue by erickfung** [spwg/wsj-scraper#1]
Hi 
I  got the error as following:
  File "C:/wsj-scraper/main.py", line 31, in insert_content
    cur.execute(sql, (url, content))
  OperationalError: no such table: wsj

Could you tell me how to fix it?

Many thanks

**Comment by spwg** [comment]
This should be fixed. I added build and run instructions to the readme.

Fixed by 083a8321722552188931be8622c116c428bdb430.

**Comment by erickfung** [comment]
Thank you for fixing it. One more question, what should I insert to the following line in python?
sql = """ INSERT INTO wsj(url, content) VALUES(?,?) """

**Comment by spwg** [comment]
Nothing! 

https://github.com/spwg/wsj-scraper/blob/083a8321722552188931be8622c116c428bdb430/main.py#L35
is where `url` and `content` are inserted into the question marks. We do it this way to avoid sql injection attacks.
